SELECT [Id]
      ,[CompanyId]
      ,[Email]
      ,[Fax]
      ,[Name]
      ,[Lastlogin]
      ,[Password]
      ,[PortalId]
      ,[RoleId]
      ,[StatusId]
      ,[Telephone]
      ,[Username]
      ,[UpdatedOn]
      ,[CreatedOn]
      ,[DeletedOn]
  FROM [RedarborDB].[dbo].[Employee]
  WHERE StatusId <> 5